### PR TITLE
puzzle examples

### PR DESCRIPTION
**Pull request by joshka**
- style: run cargo fmt
- fix: correct model for puzzle activity
- docs: extend the example code to be a cli for lichess

### CODE REVIEW

**Comment by joshka** [comment]
Command output:

`cargo run --example lichess`
```
A Rust client for Lichess API v2.0.0

Usage: lichess [OPTIONS] <COMMAND>

Commands:
  puzzle  
  help    Print this message or the help of the given subcommand(s)

Options:
  -a, --api-token <API_TOKEN>  A personal API token for lichess (https://lichess.org/account/oauth/token)
  -h, --help                   Print help
  -V, --version                Print version
```

`cargo run --example lichess -- help puzzle`
```
Usage: lichess puzzle <COMMAND>

Commands:
  daily      Get the daily puzzle
  get        Get a puzzle by its ID
  activity   Get your puzzle activity
  dashboard  Get your puzzle dashboard
  storm      Get the storm dashboard of a player
  help       Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```

`cargo run --example lichess -- help puzzle daily`

```
Get the daily puzzle

Usage: lichess puzzle daily

Options:
  -h, --help  Print help
```

`cargo run --example lichess -- puzzle daily`
```
PuzzleJson {
    game: Game {
        clock: "10+0",
        id: "3VW8NDmR",
        perf: Perf {
            key: "rapid",
            name: "Rapid",
        },
        pgn: "d4 d5 c4 e6 Nc3 dxc4 e3 Nc6 Bxc4 Nf6 Nf3 Be7 O-O Bd7 Re1 O-O a3 Re8 e4 Kh8 e5 Ng8 h4 Bxh4 Nxh4 Qxh4 Ne4 Qe7 Ng5 h6 Qh5 Rf8 Re4 g6 Qh3 Kg7 Rh4 h5 Rxh5 gxh5 Qxh5 Nh6 Ne4 Rh8 Nf6 Nf5 Qg5+ Kf8 g4 Nh4",
        players: [
            Player {
                color: "white",
                name: "Christopho (1872)",
                user_id: "christopho",
            },
            Player {
                color: "black",
                name: "M2008 (1768)",
                user_id: "m2008",
            },
        ],
        rated: true,
    },
    puzzle: Puzzle {
        id: "Gt4G9",
        initial_ply: 49,
        plays: 122023,
        rating: 1871,
        solution: [
            "g5h6",
            "h8h6",
            "c1h6",
        ],
        themes: [
            "mateIn2",
            "middlegame",
            "short",
            "sacrifice",
        ],
    },
}
```

`cargo run --example lichess -- puzzle dashboard`

```
Error: 
   0: lichess status error: Login required

Location:
   examples/lichess.rs:103

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

`cargo run --example lichess -- --api-token XXX puzzle dashboard`
```
PuzzleDashboardJson {
    days: 30,
    global: Results {
        first_wins: 0,
        nb: 1,
        performance: 831,
        puzzle_rating_avg: 1331,
        replay_wins: 0,
    },
    themes: {
        "attraction": Theme {
            results: Results {
                first_wins: 0,
                nb: 1,
                performance: 831,
                puzzle_rating_avg: 1331,
                replay_wins: 0,
            },
            theme: "Attraction",
        },
        "endgame": Theme {
            results: Results {
                first_wins: 0,
                nb: 1,
                performance: 831,
                puzzle_rating_avg: 1331,
                replay_wins: 0,
            },
            theme: "Endgame",
        },
        "fork": Theme {
            results: Results {
                first_wins: 0,
                nb: 1,
                performance: 831,
                puzzle_rating_avg: 1331,
                replay_wins: 0,
            },
            theme: "Fork",
        },
    },
}
```

**Comment by joshka** [comment]
Added tracing of request and response to mitigate #13 
I'm not sure if these should be available programmatically to a caller, but this is fine for now.
The output looks like the following:
```
cargo run --example lichess -- -v --api-token abcdefg puzzle dashboard
   Compiling lichess-api v0.1.0 (/Users/joshka/local/lichess-api)
    Finished dev [unoptimized + debuginfo] target(s) in 1.25s
     Running `target/debug/examples/lichess -v --api-token abcdefg puzzle dashboard`
2023-11-16T12:16:48.743922Z DEBUG lichess_api::client: sending request=Request { method: GET, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lichess.org")), port: None, path: "/api/puzzle/dashboard/30", query: None, fragment: None }, headers: {"accept": "application/json", "authorization": Sensitive} }
2023-11-16T12:16:48.744253Z DEBUG reqwest::connect: starting new connection: https://lichess.org/
2023-11-16T12:16:48.744396Z DEBUG hyper::client::connect::dns: resolving host="lichess.org"
2023-11-16T12:16:48.745950Z DEBUG hyper::client::connect::http: connecting to 37.187.205.99:443
2023-11-16T12:16:48.925614Z DEBUG hyper::client::connect::http: connected to 37.187.205.99:443
2023-11-16T12:16:49.903020Z DEBUG hyper::client::pool: pooling idle connection for ("https", lichess.org)
2023-11-16T12:16:49.902978Z DEBUG lichess_api::client: received response=Ok(Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lichess.org")), port: None, path: "/api/puzzle/dashboard/30", query: None, fragment: None }, status: 401, headers: {"server": "nginx", "date": "Thu, 16 Nov 2023 12:16:49 GMT", "content-type": "application/json", "content-length": "25", "connection": "keep-alive", "vary": "Origin", "x-oauth-scopes": "", "x-accepted-oauth-scopes": "puzzle:read,web:mobile", "access-control-allow-origin": "*", "access-control-allow-headers": "Origin, Authorization, If-Modified-Since, Cache-Control, Content-Type", "access-control-allow-methods": "OPTIONS, GET, POST, PUT, DELETE", "strict-transport-security": "max-age=63072000; includeSubDomains; preload", "x-frame-options": "DENY", "permissions-policy": "interest-cohort=()"} })
Error:
   0: lichess status error: No such token

Location:
   examples/lichess.rs:129

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
Though with colors:
image

**Comment by ion232** [comment]
Hi @joshka

Thank you very much for your changes and apologies for responding to this so late.

The cli app and tracing are great ideas. I've ran into bearer token and schema issues before and resorted to print statements. I was unaware that this tracing library existed, so it's a welcome change.

The puzzle example is mostly correct, but the endpoint has changed yet again, without the OpenAPI spec being updated. I'm going to merge this regardless and fix it up myself, as it only requires a small change.

I assumed that people weren't that interested in this project, so I haven't been very active with it. Thanks for sparking some joy back into it for me. I'm going to make further changes to unmothball this project, try to maintain it properly and make it more appealing for others to use. I'm interested to know what plans you had in using this library.

Thanks

**Comment by joshka** [comment]
> Thank you very much for your changes and apologies for responding to this so late.

No problems - I figured it might be a low priority library.

> The cli app and tracing are great ideas. I've ran into bearer token and schema issues before and resorted to print statements. I was unaware that this tracing library existed, so it's a welcome change.

It definitely makes things a bit easier to work with when problems happen. :)

> I assumed that people weren't that interested in this project, so I haven't been very active with it. Thanks for sparking some joy back into it for me. I'm going to make further changes to unmothball this project, try to maintain it properly and make it more appealing for others to use. I'm interested to know what plans you had in using this library.

Mostly my goals were around making it possible to add local engine analysis (see #14) to the website (to provide more cores and RAM to the analysis), but it would also be nice to have a more general CLI that can be used for various things (game exports, etc.)

> Thanks

No problem :)

**Pull request merged**
